"""Tester Agent — validates generated code structure and runs smoke tests."""

from __future__ import annotations

import ast
import textwrap
from typing import Any


class TesterAgent:
    """Validates the code generated by EngineerAgent.

    Checks performed:
    1. All planned filenames are present in the code dict.
    2. Python files parse without syntax errors.
    3. ``main.py`` or ``app.py`` contains an entry-point (``main`` function
       or FastAPI ``app`` object).
    """

    def test(
        self, code: dict[str, str], plan: dict[str, Any]
    ) -> dict[str, Any]:
        """Run validation suite.

        Returns:
            {
                "status": "pass" | "fail",
                "passed": int,
                "total": int,
                "checks": [{"name": str, "passed": bool, "message": str}],
            }
        """
        checks: list[dict[str, Any]] = []

        # Check 1: File presence
        expected_files = {t["filename"] for t in plan.get("tasks", [])}
        for fname in expected_files:
            present = fname in code
            checks.append(
                {
                    "name": f"file_present:{fname}",
                    "passed": present,
                    "message": "OK" if present else f"Missing: {fname}",
                }
            )

        # Check 2: Python syntax
        for fname, content in code.items():
            if not fname.endswith(".py"):
                continue
            ok, msg = self._check_syntax(fname, content)
            checks.append({"name": f"syntax:{fname}", "passed": ok, "message": msg})

        # Check 3: Entry-point present
        mvp_type = plan.get("mvp_type", "cli")
        entry = "main.py" if mvp_type == "cli" else "app.py"
        if entry in code:
            has_ep, ep_msg = self._check_entry_point(code[entry], mvp_type)
            checks.append(
                {"name": f"entry_point:{entry}", "passed": has_ep, "message": ep_msg}
            )

        # Check 4: Non-empty files
        for fname, content in code.items():
            non_empty = len(content.strip()) > 0
            checks.append(
                {
                    "name": f"non_empty:{fname}",
                    "passed": non_empty,
                    "message": "OK" if non_empty else "File is empty",
                }
            )

        passed = sum(1 for c in checks if c["passed"])
        total = len(checks)
        status = "pass" if passed == total else "partial" if passed > 0 else "fail"

        return {
            "status": status,
            "passed": passed,
            "total": total,
            "checks": checks,
        }

    @staticmethod
    def _check_syntax(filename: str, content: str) -> tuple[bool, str]:
        try:
            ast.parse(content)
            return True, "Syntax OK"
        except SyntaxError as exc:
            return False, f"SyntaxError at line {exc.lineno}: {exc.msg}"

    @staticmethod
    def _check_entry_point(content: str, mvp_type: str) -> tuple[bool, str]:
        try:
            tree = ast.parse(content)
        except SyntaxError:
            return False, "Cannot parse entry-point file"

        names = {
            node.name
            for node in ast.walk(tree)
            if isinstance(node, ast.FunctionDef)
        }
        assignments = {
            node.targets[0].id
            for node in ast.walk(tree)
            if isinstance(node, ast.Assign)
            and isinstance(node.targets[0], ast.Name)
        }

        if mvp_type == "web":
            if "app" in assignments or "app" in names:
                return True, "FastAPI app found"
            return False, "No FastAPI 'app' object found"

        if "main" in names:
            return True, "'main' function found"
        return False, "No 'main' function found"
